### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by KurtPachinger** [KurtPachinger/texel-gpr#1]
### bug
- [ ] box-sphere texture gap
- [ ] RNG / 1e5 (unhelpful?)

### feature
- [ ] depth mesh from NURBs/splines
- [ ] depth mesh from (OpenCV?) texels
  - [ ]  n process / depth
  - [ ] Perlin noise ( resistance +/- radius)
  - [ ] sample rgb area average
- [ ] cloudmap

- [ ] multiple textures (file/checkbox) for depth(s)/planet(s)
